boxes <- c(
  "mvgowxqubnhaefjslkjlrptzyi",
  "pvgowlqubnhaefmslkjdrpteyi",
  "ovgowoqubnhaefmslkjnrptzyi",
  "cvgowxqubnrxefmslkjdrptzyo",
  "cvgowxqubnhaefmsokjdrprzyf",
  "cvgowxqubnhjeflslkjgrptzyi",
  "cvgowxqvbnhaefmslkhdrotzyi",
  "hvgowxqmbnharfmslkjdrptzyi",
  "cvgoaxqubqhaefmslkjdrutzyi",
  "cvxowxqdbnhaefmslkjdgptzyi",
  "cvgikxqubnhaefmslkjdrptzyz",
  "cvgnwxqubnhaqfjslkjdrptzyi",
  "cqgowxqubnhaecmslkjgrptzyi",
  "cvpowxqucnhaefmslkjdrptzyz",
  "fvuoexqubnhaefmslkjdrptzyi",
  "svgowxqubnhaefmsvkjdrttzyi",
  "cvgowxqubnhaefmblkjdfpbzyi",
  "cvkoyxqubnhaefsslkjdrptzyi",
  "bvgowxqublhaefmslkjdrptzfi",
  "xvgewxqubnhaefmslkjdrztzyi",
  "cvgowxqubzhaefmslkkrrptzyi",
  "cvgowxqubnhaefmslkudruuzyi",
  "cvgowxqubnhaefmvlkjdrptwyl",
  "cvgoyxqubnhaefmslkjvrotzyi",
  "cvgowxoubnhaewmslkjdrpbzyi",
  "cvgowxgubnhaefmslijdrptzxi",
  "lvgowxqkbnhaefmslkjdrptzqi",
  "xvgowxqubyhaefmflkjdrptzyi",
  "wvnowxgubnhaefmslkjdrptzyi",
  "cvgowxguwnhaefhslkjdrptzyi",
  "cvgowfquxnhaefmdlkjdrptzyi",
  "cvgywxqubnuaefmsldjdrpfzyi",
  "cvkowxqzbrhaefmslkjdrptzyi",
  "cviowxzubnhaefmslkjdrptqyi",
  "cvgowxqubnhaefmsozjdrptzyc",
  "cvglwxuubnhaewmslkjdrptzyi",
  "cvgowxquknhaebmsfkjdrptzyi",
  "vvgowxqubnhaesmslkjdrptzri",
  "cvgowxoubndaefmslkjdrftzyi",
  "cvgowxqubghaefmslkjdeptzyw",
  "cvgowxqubnhaetmhlkjdrpvzyi",
  "cvgowmquunhaefmslkjdrptzyt",
  "cvgooxqpbniaefmslkjdrptzyi",
  "cvgowxqubnhaeumslkjdkptiyi",
  "cvgrwxqsbnhaemmslkjdrptzyi",
  "cvrowxqubnhaefmslkjdrctcyi",
  "dvgcwxqubnhaefmslkjdrptzyq",
  "cugowxqubnhasfmmlkjdrptzyi",
  "cwgowxqobzhaefmslkjdrptzyi",
  "cvgowxquwnhaefmulkjdrptbyi",
  "nvgowxqmbnhaefmslyjdrptzyi",
  "cvgowxqubniakvmslkjdrptzyi",
  "cvyowxqubnhaefmslejdrptzyx",
  "cvgobxqubghaefeslkjdrptzyi",
  "cvgowxiubnhaebmslkjdfptzyi",
  "cvgosbqubnhaefmslkvdrptzyi",
  "cvgpwxqubnhaefvslkjdrptzyh",
  "cvgowxqubnyaefmslgjdsptzyi",
  "cvgowxqubnhaefmslkjdrprzzp",
  "cvgowxqubwhaemmslkjdrpazyi",
  "cvgowxqpbnhaemmslkjdrpczyi",
  "cvgoqxqubnhaelmslkjdrptzye",
  "cvgowxqubnhaefmslbjdrttzvi",
  "cvgowxqubnhlefmslkvurptzyi",
  "cvgowxqujngaefmslktdrptzyi",
  "cvgowxqubnhaefmsckjdcwtzyi",
  "cvcowxqubnhaetmslkjorptzyi",
  "jvnowxqubnhaefmslkjdrptzyf",
  "cygowxqkbnhaefmslejdrptzyi",
  "cvmowxqubnhaefmslkjdritzoi",
  "cvgowxqubnpaefmslkjdrpnnyi",
  "cvgowxqubnhaefmolkjdrpnzyy",
  "uvgowxoubnhaefmslkjdrptzvi",
  "cvgowxbabehaefmslkjdrptzyi",
  "cvgokxqubnhaefmsckjdrjtzyi",
  "cvgoxwqubahaefmslkjdrptzyi",
  "cvgowxqusnhaefmslijdrptyyi",
  "cvgowxqubmhaeqmslkxdrptzyi",
  "cvgouxhubnhaefmslkjdrjtzyi",
  "cvgowxqubnhaefmslrjdqptzyk",
  "cvgowxiublhaefsslkjdrptzyi",
  "cvgowxqubnxgefmslkadrptzyi",
  "ovgowxqugshaefmslkjdrptzyi",
  "cvgowxquznhaeemslsjdrptzyi",
  "cvkowxqubnhaeomslkjdeptzyi",
  "cvgvwxqubxhaefmslkjdrptzyu",
  "cvglwxqybnhaefmslkjdrptzyb",
  "cvgowxqubnlfwfmslkjdrptzyi",
  "cvaowxqubnhaefmslkjdrvtzbi",
  "cvgowxqubnrmefaslkjdrptzyi",
  "cvgowxqubnhaefmsnkjdfpwzyi",
  "cvgawxqmbnhaefmsykjdrptzyi",
  "chgowmqubnhaefmslkjdrptwyi",
  "cogowxqubnhaefmslkjxrptzri",
  "cvgohxqubnoaesmslkjdrptzyi",
  "cvdowxqubnhaofmslkjdrpvzyi",
  "vvgowrqubnhaefmslkjdrpthyi",
  "cvgowxquknhuefmslkjdoptzyi",
  "cvyowxeubnhaefmslhjdrptzyi",
  "cvglwxqubnhaefmslkjdrptdyq",
  "cvgowxqubnhaefmsikgdrptayi",
  "cvgowxqubnhaefjhlkjdrpczyi",
  "cvgzwxkubnhaefmslkjdjptzyi",
  "cxgowxqubnhaefmslkjdrptwyy",
  "cvgowxqubnhaefeslkjdrmqzyi",
  "cvgowxvubnhaefmilijdrptzyi",
  "cvgowxqzbthaeomslkjdrptzyi",
  "cvgowhqubndaefmglkjdrptzyi",
  "cvgowxvubnhaeamylkjdrptzyi",
  "cvgowiqubnhgefmslkjdrctzyi",
  "cvgowxqubchaefmslksdritzyi",
  "cvgowxqubnhaefmsnkjdreyzyi",
  "cvgowxqubihaefmslkgdrutzyi",
  "cvgowxqjbnhaeamslkjdrptzwi",
  "cvgowxzubnhaefmsxkjdrrtzyi",
  "cvgowxqubyhaetmslnjdrptzyi",
  "cvgowxquhnhaebmslkjdxptzyi",
  "cvgowxqubnhanfmslujdxptzyi",
  "cvgowxqublhnefaslkjdrptzyi",
  "cvgmwxqtbnhaefmslkjsrptzyi",
  "jvgowxqubnhaeamslkjdrpmzyi",
  "cvgowxqubhiaefmsljjdrptzyi",
  "svgowxqubnhaefmswkjdrpozyi",
  "cvgowxqebnhaeqmslkjdiptzyi",
  "cveowxqubnhayzmslkjdrptzyi",
  "cvglwxqubnhaefmxlkjdiptzyi",
  "cvgowkqubdhaefmszkjdrptzyi",
  "cvgowxkxbnhaeffslkjdrptzyi",
  "cugowxqubnnaefmslujdrptzyi",
  "cqgowxwubnhaepmslkjdrptzyi",
  "cvgowxqubnhayfmmlkjwrptzyi",
  "cvgowxquenhaefmsskxdrptzyi",
  "cvgowxqubnhiefmsrkjdtptzyi",
  "mvgowxkubnhaefmjlkjdrptzyi",
  "cvgowkquunhaefmglkjdrptzyi",
  "cvgowxqubqhaexmslgjdrptzyi",
  "jvgowxqubnhaefmslkjddptlyi",
  "cvgiwxqubnhaefmslkjdpptmyi",
  "czgowxqubntaevmslkjdrptzyi",
  "cvgotmqubnhaefmslkjdrpazyi",
  "cvgowxtubnhaefmslkqdtptzyi",
  "cvbowxqhnnhaefmslkjdrptzyi",
  "cvgowkqubshaefmstkjdrptzyi",
  "cvgowqqrbnaaefmslkjdrptzyi",
  "cvgoixqubnhaefmslkjdrpmryi",
  "cvgoxxqubnhaeimsxkjdrptzyi",
  "cvgowxqubzhaebmslkjyrptzyi",
  "cjgewxqubnhaefsslkjdrptzyi",
  "cvgowxqdbnkaefmslwjdrptzyi",
  "cvgowxqzbnhaeamslkjdrftzyi",
  "cvgoixqubnsaewmslkjdrptzyi",
  "cvgswxqubnhaxfmslkjdrptzni",
  "cvwowxmubnhgefmslkjdrptzyi",
  "cvggwxqubnhaefmslqjdbptzyi",
  "cvgzwxqjbnhaefaslkjdrptzyi",
  "cvgowzqubnharfmspkjdrptzyi",
  "cvgowxqubnhawfmslkjdeptzyb",
  "cvuowequbnhaefmslkjdrntzyi",
  "gvgowxqubnxaefmslkjdrjtzyi",
  "cvgowxqubnhmetmsldjdrptzyi",
  "cvgowxqubnhamfmsqkjdrptyyi",
  "cvgoqxqubnhaefmslkjtrpazyi",
  "cvgoexqubhhaefmslkjdrhtzyi",
  "cvgowwqubnhaeflslkjdrptzyf",
  "cvgowlpubnhaefmslkjdrptvyi",
  "cvgowxouunhaebmslkjdrptzyi",
  "cvdowhqubnhaefmslijdrptzyi",
  "cvgowxqubnkatfmslkjdrhtzyi",
  "cvgowxqpbnhxeumslkjdrptzyi",
  "cvgowxqubnhaefmsukjjrptzyn",
  "cvgowxqubnhmefmslzjdrvtzyi",
  "cvtowxqubihaefmclkjdrptzyi",
  "chgowcqubnhayfmslkjdrptzyi",
  "cvguwxqubnhaefmblkjarptzyi",
  "cvgowoqubnhaefmsikjdrytzyi",
  "cvgkwxqubnhaefmslkjdrptchi",
  "cvhowxqubnhaefmslkjdrvlzyi",
  "cvlowxfubnhaefmslkjkrptzyi",
  "cvgowxqubhhaefoslkjdrytzyi",
  "cvgowxsubqhaefmslpjdrptzyi",
  "cvgowxpubnhaefmslhjdrptzyb",
  "cvgowxqubnhrefmjlkddrptzyi",
  "cvgowxqubnhaxfmykkjdrptzyi",
  "mvgowxqubnhakfmslkjdrptnyi",
  "cwgowxqubnhaffmslkadrptzyi",
  "chgowxquwnhaefmslsjdrptzyi",
  "cvgowxqubnhaefmslkjdwpnsyi",
  "cvgawxqubnhaefmslkldyptzyi",
  "cvgowxqubnhiefmslkjdiprzyi",
  "cvgkqxqubnhaefcslkjdrptzyi",
  "cvgovoqubnhaefmslkjdrpuzyi",
  "cvgowxqubnhaefmszkjdrjtzyk",
  "cvgopxqubnhaefmslkjdqpnzyi",
  "cvgtwxqubnhaefmslkjnrptzri",
  "cvgowxqurnhaedmslfjdrptzyi",
  "cvpowxqubnhaefmswkjdrltzyi",
  "cvgowxqujnpaefmslkjdrptdyi",
  "cvgowgqubnhzifmslkjdrptzyi",
  "lvgowxqubnhaenmslkjdbptzyi",
  "ebgowxqubnhaeymslkjdrptzyi",
  "cvgowxtubqhaefmslkedrptzyi",
  "cvgowxqubshaesmslkjdrptryi",
  "cvgowxqubnhaefmflkjmrpkzyi",
  "cvgowxqubngaefmslkjdrytzgi",
  "cvgowxqubnhaefmslklhzptzyi",
  "cveowxqubnhgefmslkjdrpezyi",
  "cvgowxqubnhaeomslkjdrqtzym",
  "cvgowxqubzhaefmslwjdrptfyi",
  "cmgowxqubnhaefmsdkjdrptzui",
  "cvlowxqubnhaefmslsjdrptzwi",
  "cvhowxpubnhaefmslkjhrptzyi",
  "cveosxqurnhaefmslkjdrptzyi",
  "cvgowxqubnhaefgsdkjdrptjyi",
  "cvgvwxqubnhaefmslzjdmptzyi",
  "cviowxqubnhalfmslkjdrptzyr",
  "cvgowxqubchqefmslkjdrptzoi",
  "cvgownqubnhaefmsyktdrptzyi",
  "cvgywxqubnuaefmslkjdrpfzyi",
  "cvgobxqunnhaefmslkjdrptzbi",
  "cvgowxqubshaefgslkjdrxtzyi",
  "cvghwxqubnhaefmslkjdrbtmyi",
  "cvhowxqubnhaefmslkjdrpnzys",
  "cvgowxqubnmaefmslejdrptzyq",
  "cvmrwxqubnhaefmslkjdrpzzyi",
  "cvgowxqubshaefmslkfdrptzyu",
  "cvgowqqubnhaefmslkodrpjzyi",
  "cvgnwnquknhaefmslkjdrptzyi",
  "cvgowxquxnhacfmflkjdrptzyi",
  "ovgowxqubnhaefmslkjmrmtzyi",
  "cvgowxqubneaefmslkedrptzqi",
  "cvgowxqubphweflslkjdrptzyi",
  "cvgowxqudnhaefmplkjdrptdyi",
  "cvwowxbubnhaefmslkjurptzyi",
  "cvgowxtubnhaefmslkjdrwwzyi",
  "cvgowxqubnhkefmslajdrptzyn",
  "cvgowxqxbphaefmslkjdrptzsi",
  "cvgowxquenhaefmslmjwrptzyi",
  "zvgowdqubnhaeftslkjdrptzyi",
  "csgowxqubnhgefmslkjdrptzyy",
  "cvgolxqubahaefmslkjdrpvzyi",
  "cvgoqxquhwhaefmslkjdrptzyi",
  "cvgawxqubghaefmsrkjdrptzyi",
  "cvgozxqubnhaefmslkwdfptzyi",
  "cvgowxqubnhaefmslhjdkptzzi",
  "cvnowxqubnhaefmsqkjdrptqyi",
  "cvpowxqubnhaefmslkpdrptdyi",
  "cvgowxoubnhaermslkjdrctzyi",
  "cvgowxqubnheefmslkjdrctzyr",
  "cvgowxqunnhaqfhslkjdrptzyi",
  "cvgowxqulnhaefmslrjdrntzyi"
)

split_string <- function(string) {
  nlets <- nchar(string)
  out <- vector("character", length = nlets)
  
  for (i in seq.int(nlets)) {
    out[i] <- substr(string, i, i)
  }
  
  out
}

split_string(boxes[1])

letter_rep <- function(string, n) {
  splt_str <- split_string(string)
  
  for (i in seq_along(splt_str)) {
    curr_letter <- splt_str[i]
    remaining_letters <- splt_str[-i]
    
    if (sum(curr_letter == remaining_letters) == (n-1)) return(TRUE)
  }
  
  FALSE
}

letter_rep("abcdef", 2)
letter_rep("bababc", 2)
letter_rep("abbcde", 2)

twos <- sapply(boxes, letter_rep, 2)
threes <- sapply(boxes, letter_rep, 3)

checksum <- sum(twos) * sum(threes)
checksum # answer 1

for (i in seq_along(boxes)) {
  curr_box <- split_string(boxes[i])
  remaining_boxes <- lapply(boxes[-i], split_string)
  
  for (b in remaining_boxes) {
     if (sum(curr_box != b) == 1) {
       b1 <- curr_box
       b2 <- b
       break
     }
  }
}

paste0(b1[b1 == b2], collapse = "") # answer 2
